siso: need to use canonpath on android .sources file
after

❯ RBE_exec_strategy=remote autoninja -C out/rbe-android base/version_info/android:version_constants_java
Proxy started successfully.
 2.97s load build.ninja
build finished: <nil>
13.40s Build Succeeded: 5 steps - 0.37/s
RBE Stats: down 4.66 KB, up 950 B, 1 remote execution

before

❯ RBE_exec_strategy=remote autoninja -C out/rbe-android base/version_info/android:version_constants_java
Proxy started successfully.
 2.95s load build.ninja
pre:0 local:0 remote:1 fallback:0
FAILED: 280bff3d-4c62-4faf-8c21-f61b5c4e350f ACTION //base/version_info/android:version_constants_java__errorprone(//build/toolchain/android:android_clang_arm64)
stdout:
Traceback (most recent call last):
  File "/b/f/w/set_by_reclient/a/../../build/android/gyp/compile_java.py", line 856, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/b/f/w/set_by_reclient/a/../../build/android/gyp/compile_java.py", line 845, in main
    md5_check.CallAndWriteDepfileIfStale(lambda changes: _OnStaleMd5(
  File "/b/f/w/build/android/gyp/util/md5_check.py", line 54, in CallAndWriteDepfileIfStale
    CallAndRecordIfStale(
  File "/b/f/w/build/android/gyp/util/md5_check.py", line 123, in CallAndRecordIfStale
    new_metadata.AddFile(path, _ComputeTagForPath(path))
  File "/b/f/w/build/android/gyp/util/md5_check.py", line 441, in _ComputeTagForPath
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'gen/base/version_info/android/java/org/chromium/base/version_info/VersionConstants.java'
build finished: cannot make progress due to previous 1 errors
9.12s Build Failure: 1 done 1 failed 5 remaining - 0.11/s
 cannot make progress due to previous 1 errors
see ./out/rbe-android/siso_output for command line and output
 or ./out/rbe-android/siso.INFO
RBE Stats: down 415 B, up 0 B, 1 non zero exit

Cq-Include-Trybots: luci.chromium.try:fuchsia-binary-size-siso
Cq-Include-Trybots: luci.chromium.try:ios-simulator-siso
Cq-Include-Trybots: luci.chromium.try:linux_chromium_asan_siso_rel_ng
Cq-Include-Trybots: luci.chromium.try:linux_chromium_compile_siso_dbg_ng
Cq-Include-Trybots: luci.chromium.try:mac-siso-rel
Bug: b/325386142
Change-Id: I33e22d33cafbde2d167afa62d7454cb21655ce86
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5299574
Reviewed-by: Junji Watanabe <jwata@google.com>
Reviewed-by: Fumitoshi Ukai <ukai@google.com>
Commit-Queue: Richard Wang <richardwa@google.com>
Cr-Commit-Position: refs/heads/main@{#1260951}
NOKEYCHECK=True
GitOrigin-RevId: 865d0f8a5751abc1ea2606e90994e46f39f155fe