Revert "Add rust_gtest_interop_unittests on ~all bots that run base_unittests"
This reverts commit 55cff755dae2b480964c463313a58cbd2358ec9c.

Reason for revert: FAILED: librust_gtest_interop_unittests_rust_objects.rlib
"python3" "/Volumes/Work/s/w/ir/cache/builder/src/build/rust/rustc_wrapper.py" --rustc=../../third_party/rust-toolchain/bin/rustc --depfile=./librust_gtest_interop_unittests_rust_objects.rlib.d -- error: unsupported relocation of variable 'L_anon.0a6c0c0bcbf25d0afd021f67f591ed7c.4'

error: unsupported relocation of variable 'L_anon.0a6c0c0bcbf25d0afd021f67f591ed7c.8'

error: unsupported relocation of variable 'L_anon.0a6c0c0bcbf25d0afd021f67f591ed7c.10'

error: unsupported relocation of variable 'L_anon.0a6c0c0bcbf25d0afd021f67f591ed7c.12'

error: unsupported relocation of variable 'L_anon.0a6c0c0bcbf25d0afd021f67f591ed7c.15'

error: unsupported relocation of variable 'L_anon.64642c20d38f7c67a388714a89359d38.5'

error: unsupported relocation of variable 'L_anon.64642c20d38f7c67a388714a89359d38.9'

error: unsupported relocation of variable 'L_anon.64642c20d38f7c67a388714a89359d38.11'

error: unsupported relocation of variable 'L_anon.64642c20d38f7c67a388714a89359d38.13'

error: unsupported relocation of variable 'L_anon.64642c20d38f7c67a388714a89359d38.15'

error: unsupported relocation of variable 'L_anon.64642c20d38f7c67a388714a89359d38.38'

error: aborting due to 11 previous errors

Original change's description:
> Add rust_gtest_interop_unittests on ~all bots that run base_unittests
>
> Enable compilation of the test suite globally, and add it to the set
> of tests that bots run.
>
> The test suite is 10 tests large, so it's very quick to build and run.
>
> iOS is excluded as framework_dirs breaks GN for generating Ninja
> rules of Rust targets.
>
> Bug: 1293979, gn:340
> Change-Id: If3fff290b5e7597a93b94ba70f097e95235f2434
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4653253
> Auto-Submit: danakj <danakj@chromium.org>
> Commit-Queue: danakj <danakj@chromium.org>
> Reviewed-by: Ben Pastene <bpastene@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1164801}

Bug: 1293979, gn:340
Change-Id: I7f580d32ec2c66d39dc2445e95e46c6ffe1343e3
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4659391
Owners-Override: S Ganesh <ganesh@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Auto-Submit: S Ganesh <ganesh@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Cr-Commit-Position: refs/heads/main@{#1164815}
NOKEYCHECK=True
GitOrigin-RevId: 23e41f75aa94387a1bd7d0e7549449b464257696