Revert "build: fix deps for system_webview_64_apk__compile_resources"
This reverts commit de17bb41604c6af4325900d8d8aaf03e127bda54.

Reason for revert: Reason for revert: Reason for revert: As already mentioned on the bug, https://crrev.com/c/5172710 suspected of causing failures on the deterministic build bot. Reverting all CLs that landed after it, because of merge conflicts. (Revert 3/4)

Original change's description:
> build: fix deps for system_webview_64_apk__compile_resources
>
> This is to fix error like
> ```
> FALLBACK 19a88ddc-14d8-4fe7-8c68-6791ce07c1bd ACTION //android_webview:system_webview_64_apk__compile_resources(//build/toolchain/android:android_clang_x64)
> err: fallback in reproxy exit=1
> siso_rule:android/compile_resources
> digest:4c7815c78acfdd146c776ba4728e6c829f3c187593e98f3c662b88f9ca410293/147
> "__android_webview_system_webview_64_apk__compile_resources___build_toolchain_android_android_clang_x64__rule" "./gen/android_webview/system_webview_64_apk__compile_resources.srcjar"
> python3 ../../build/android/gyp/compile_resources.py --include-resources=../../third_party/android_sdk/public/platforms/android-34/android.jar --aapt2-path ../../third_party/android_build_tools/aapt2/aapt2 --dependencies-res-zips=@FileArg\(gen/android_webview/system_webview_64_apk.build_config.json:deps_info:dependency_zips\) --extra-res-packages=@FileArg\(gen/android_webview/system_webview_64_apk.build_config.json:deps_info:extra_package_names\) --min-sdk-version=26 --target-sdk-version=34 --webp-cache-dir=obj/android-webp-cache --android-manifest gen/android_webview/system_webview_64_apk/AndroidManifest.merged.xml --srcjar-out gen/android_webview/system_webview_64_apk__compile_resources.srcjar --version-code 625200009 --version-name 122.0.6252.0 --arsc-path obj/android_webview/system_webview_64_apk.ap_ --info-path obj/android_webview/system_webview_64_apk.ap_.info --r-text-out gen/android_webview/system_webview_64_apk__compile_resources_R.txt --shared-resources --dependencies-res-zip-overlays=@FileArg\(gen/android_webview/system_webview_64_apk.build_config.json:deps_info:dependency_zip_overlays\) --proguard-file obj/android_webview/system_webview_64_apk/system_webview_64_apk.resources.proguard.txt --locale-allowlist=\[\"af\",\ \"am\",\ \"ar\",\ \"as\",\ \"az\",\ \"be\",\ \"bg\",\ \"bn\",\ \"bs\",\ \"ca\",\ \"cs\",\ \"da\",\ \"de\",\ \"el\",\ \"en-GB\",\ \"en-US\",\ \"es\",\ \"es-419\",\ \"et\",\ \"eu\",\ \"fa\",\ \"fi\",\ \"fil\",\ \"fr\",\ \"fr-CA\",\ \"gl\",\ \"gu\",\ \"he\",\ \"hi\",\ \"hr\",\ \"hu\",\ \"hy\",\ \"id\",\ \"is\",\ \"it\",\ \"ja\",\ \"ka\",\ \"kk\",\ \"km\",\ \"kn\",\ \"ko\",\ \"ky\",\ \"lo\",\ \"lt\",\ \"lv\",\ \"mk\",\ \"ml\",\ \"mn\",\ \"mr\",\ \"ms\",\ \"my\",\ \"nb\",\ \"ne\",\ \"nl\",\ \"or\",\ \"pa\",\ \"pl\",\ \"pt-BR\",\ \"pt-PT\",\ \"ro\",\ \"ru\",\ \"si\",\ \"sk\",\ \"sl\",\ \"sq\",\ \"sr\",\ \"sr-Latn\",\ \"sv\",\ \"sw\",\ \"ta\",\ \"te\",\ \"th\",\ \"tr\",\ \"uk\",\ \"ur\",\ \"uz\",\ \"vi\",\ \"zh-CN\",\ \"zh-HK\",\ \"zh-TW\",\ \"zu\",\ \"ar-XB\",\ \"en-XA\"\] --png-to-webp --webp-binary clang_x64/cwebp --resource-exclusion-regex=drawable\[\^/\]\*-xxxhdpi\|-watch\\b\|-ldpi\\b\|mediarouter.\*\?drawable-x\?hdpi --resource-exclusion-exceptions=\[\"\*shadow\*\",\ \"\*.9.\*\",\ \"\*ic_group_\*\"\] --emit-ids-out=gen/android_webview/system_webview_64_apk__compile_resources.resource_ids --manifest-package=com.google.android.webview.debug --depfile gen/android_webview/system_webview_64_apk__compile_resources.d
> stdout:
> Traceback (most recent call last):
>   File "/b/f/w/set_by_reclient/a/../../build/android/gyp/compile_resources.py", line 1015, in <module>
>     main(sys.argv[1:])
>   File "/b/f/w/set_by_reclient/a/../../build/android/gyp/compile_resources.py", line 944, in main
>     manifest_package_name = _PackageApk(options, build)
>   File "/b/f/w/set_by_reclient/a/../../build/android/gyp/compile_resources.py", line 851, in _PackageApk
>     protoresources.HardcodeSharedLibraryDynamicAttributes(
>   File "/b/f/w/build/android/gyp/util/protoresources.py", line 211, in HardcodeSharedLibraryDynamicAttributes
>     _ProcessZip(zip_path, process_func)
>   File "/b/f/w/build/android/gyp/util/protoresources.py", line 46, in _ProcessZip
>     new_data = process_func(info.filename, data)
>   File "/b/f/w/build/android/gyp/util/protoresources.py", line 208, in process_func
>     data = xml_node.SerializeToString()
>   File "/b/f/w/set_by_reclient/a/../../third_party/protobuf/python/google/protobuf/internal/python_message.py", line 1086, in SerializeToString
>     return self.SerializePartialToString(**kwargs)
>   File "/b/f/w/set_by_reclient/a/../../third_party/protobuf/python/google/protobuf/internal/python_message.py", line 1095, in SerializePartialToString
>     self._InternalSerialize(out.write, **kwargs)
>   File "/b/f/w/set_by_reclient/a/../../third_party/protobuf/python/google/protobuf/internal/python_message.py", line 1107, in InternalSerialize
>     if descriptor.GetOptions().map_entry:
>   File "/b/f/w/set_by_reclient/a/../../third_party/protobuf/python/google/protobuf/descriptor.py", line 166, in GetOptions
>     from google.protobuf import descriptor_pb2
> ImportError: cannot import name 'descriptor_pb2' from 'google.protobuf' (/b/f/w/set_by_reclient/a/../../third_party/protobuf/python/google/protobuf/__init__.py)
> ```
> in
> https://ci.chromium.org/ui/p/chromium/builders/try/android-12-x64-rel/654517/overview
>
> Bug: b/315080809
> Change-Id: I3df1936808f39d083db38e8c83d77bc210a85969
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5198444
> Reviewed-by: Junji Watanabe <jwata@google.com>
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Auto-Submit: Takuto Ikuta <tikuta@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1247894}

Bug: b/315080809, 1518973
Change-Id: I24c3cf8e368e62691e35e261281490ef4603c56f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5210871
Reviewed-by: Junji Watanabe <jwata@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Ioana Pandele <ioanap@chromium.org>
Commit-Queue: Ioana Pandele <ioanap@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1248709}
NOKEYCHECK=True
GitOrigin-RevId: 7da53303edd50d982c6b7d22916e74bad664bc9e