Revert "[Fuchsia] Create ssh config dir if needed"
This reverts commit bed3c16946bb65c3808b37f68a8af2b0576e3d53.

Reason for revert: Causing flakes during task execution. See https://chromium-swarm.appspot.com/task?id=6212c1acf5983a10

FileExistsError: [Errno 17] File exists: '/home/chrome-bot/.fuchsia'

Original change's description:
> [Fuchsia] Create ssh config dir if needed
>
> Bug: 1442891
> Change-Id: I4955502e849bfe098f087fb00c473450bcf374e2
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4505164
> Commit-Queue: Chong Gu <chonggu@google.com>
> Commit-Queue: Zijie He <zijiehe@google.com>
> Auto-Submit: Chong Gu <chonggu@google.com>
> Reviewed-by: Zijie He <zijiehe@google.com>
> Cr-Commit-Position: refs/heads/main@{#1140459}

Bug: 1442891
Change-Id: I80f35addfaf48b42e7973101c3bb1662461b08a5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4514296
Reviewed-by: Rohan Pavone <rohpavone@chromium.org>
Reviewed-by: Zijie He <zijiehe@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rohan Pavone <rohpavone@chromium.org>
Auto-Submit: Rohan Pavone <rohpavone@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1141001}
NOKEYCHECK=True
GitOrigin-RevId: 612966f12f7b03d16a9079d552d58f54ac54bea5